[project]
name = "albert-llm"
version = "0.1.0"
description = "Albert LLM API"
authors = [
    {name = "Etalab", email = "etalab@modernisation.gouv.fr"},
]
#dependencies = [
#    "fastapi",
#    "gpt4all",
#    "huggingface-hub",
#    "python-dotenv",
#    "pyyaml",
#    "torch",
#    "transformers",
#    "uvicorn",
#]
dependencies = [
    "fastapi==0.103.1",
    "gpt4all==2.2.1",
    "huggingface-hub==0.20.3",
    "python-dotenv",
    "pyyaml==6.0.1",
    "torch==2.2.2",
    "transformers==4.39.3",
    "uvicorn==0.23.2",
]
#dependencies = [
#    "fastapi",
#    # pas d'erreur CPU mais les binaires sont cassés...
#    "gpt4all==0.3.0",
#    "huggingface-hub",
#    "python-dotenv",
#    "pyyaml",
#    "torch",
#    "transformers",
#    "uvicorn",
#]
requires-python = "==3.10.*"
license = {text = "MIT"}

[tool.setuptools]
py-modules = []

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore-init-module-imports = true

[tool.ruff.lint.isort.sections]
pyalbert = ["pyalbert"]
